### ISSUE TITLE
Very low Scores

### ISSUE THREAD

**Issue by Peter-72** [thomeou/SALSA#12]
@thomeou @karnwatcharasupat 

When training the SALSA model, I get very low and bad scores that are nowhere near the scores presented in the paper. Here is the configs that I used:

NB: I cannot use more `FFTs` because they are unfittable in my RAM when concatenating the file name arrays.

1. For extracting the salsa feature:
  ```
  data:
    format: 'foa'
    fs: 24000
    n_fft: 256
    win_len: 256
    hop_len: 150
    fmin_doa: 50
    fmax_doa: 9000
  ```
2. For training:
```
# MAP config
name: 'map'
feature_root_dir: 'dataset/features/salsa/foa/24000fs_256nfft_150nhop_5cond_9000fmaxdoa'
feature_type: 'salsa'
gt_meta_root_dir: 'dataset/data'
split_meta_dir: 'dataset/meta/dcase2021/original'
seed: 2021
mode: 'crossval'
data:
  fs: 24000
  n_fft: 256
  hop_len: 300
  n_mels: 200
  audio_format: 'foa' 
  label_rate: 10
  train_chunk_len_s: 8
  train_chunk_hop_len_s: 0.5
  test_chunk_len_s: 60.0
  test_chunk_hop_len_s: 60.1
  n_classes: 12
  train_fraction: 1.0
  val_fraction: 1.0
  output_format: 'reg_xyz'
model:
  encoder:
    name: 'PannResNet22'
    n_input_channels: 7
  decoder:
    name: 'SeldDecoder'
    decoder_type: 'bigru'
    decoder_size: 256
    freq_pool: 'avg'
training:
  train_batch_size: 32
  val_batch_size: 32
  optimizer: 'adam'
  lr_scheduler:
    milestones:
      - 0.0
      - 0.1
      - 0.7
      - 1.0
    lrs:
      - 3.e-4
      - 3.e-4
      - 3.e-4
      - 1.e-4
    moms:
      - 0.9
      - 0.9
      - 0.9
      - 0.9
  loss_weight:
    - 0.3
    - 0.7
  max_epochs: 50
  val_interval: 1
sed_threshold: 0.3
doa_threshold: 20
eval_version: '2021'
```

And these are the results I obtained with these settings:
```
2021 SELD metrics: SELD error: 0.794 - SED ER: 1.027 - SED F1: 0.045 - DOA LE: 68.594 - DOA LR: 0.186
```
and
```
DATALOADER:0 TEST RESULTS
{'valER': 1.0272366522366523,
 'valF1': 0.0449490538573508,
 'valLE': 68.59412559532619,
 'valLR': 0.18617164379876244,
 'valSeld': 0.7942986075275322}
```

On the other hand, I trained the `linspeciv` feature with the same configs, and the scores where very good:
```
2021 SELD metrics: SELD error: 0.308 - SED ER: 0.472 - SED F1: 0.656 - DOA LE: 12.650 - DOA LR: 0.652

DATALOADER:0 TEST RESULTS
{'valER': 0.4717712842712843,
 'valF1': 0.6562263960924518,
 'valLE': 12.649613618929243,
 'valLR': 0.6522505064740597,
 'valSeld': 0.30839250323026157}
```

So, what is exactly the problem? What am I doing wrong?

@andres-fr what scores did you obtain when you trained the model?
